---
title: "Validating Community Assembly Rules Project Data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Validating Community Assembly Rules Project Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(commruleR)
```

## Load data specific to the Comm Assembly Rules project stored in this package

```{r, start, echo=TRUE}
# Validate package rules
data(commassembly_rules_biomass_str)
data(commassembly_rules_env_str)

# list of URLS from google drive to a data sheet
doc_with_list_url <- Sys.getenv('TEST_ID_LIST_URL')
id_column = 'ID_new'
urls.df <- read_url_list(gurl = doc_with_list_url, id_column = id_column, url_column='url')
```

Read in the first URL as a test.  There will be warnings if the columns are not the correct type or name

```{r, read_one_biomass, echo=TRUE}
# read in one, and validate the column names
# this will throw warnings if there are invalid column names
biomass.df <- read_commassemblyrules_sheet(urls.df$url[1], sheet = 'biomass_data', spec.df = commassembly_rules_biomass_str)
env.df <- read_commassemblyrules_sheet(urls.df$url[1], sheet = 'env_data', spec.df = commassembly_rules_env_str)
head(biomass.df)
```

